language: go

go:
 - 1.7.6
 - 1.8.3
 - 1.9
services:
 - mysql
before_script:
 - mysql -e "create database IF NOT EXISTS test;" -uroot
env:
 - MYSQL_CONNECTION='travis@tcp(127.0.0.1:3306)/test'
script: make test-integration
