--- 
artifacts: 
  files: bendo/bendo.tar.gz
environment_variables: 
  plaintext: 
    GOPATH: "/opt/bendo/gocode:/opt/bendo/gocode/Godeps/_workspace"
phases: 
  build: 
    commands: 
      - "cd /opt/bendo/gocode && go get github.com/ndlib/bendo/bendo"
  install: 
    commands: 
      - "apt-get install git"
  pre_build: 
    commands: 
      - "mkdir /opt/bendo"
      - "mkdir -p /opt/bendo/gocode"
      - "mkdir -p /opt/bendo/gocode/{src,pkg,bin}"
      - "chmod -R 755 /opt/bendo"
version: 0.1

